### ISSUE TITLE
HiddenLayer2.swift:41:79: Ambiguous use of operator '+'

### ISSUE THREAD

**Issue by johndpope** [morpheby/Seconn-Swift#1]
<img width="1399" alt="screen shot 2018-08-22 at 9 24 22 am" src="https://user-images.githubusercontent.com/289994/44466003-3338e900-a5ed-11e8-8a28-72ddf180ea7a.png">

**Comment by johndpope** [comment]
@morpheby - any ideas?

**Comment by morpheby** [comment]
@johhdpope, sorry, morpheby/Surge fork is out of sync. You can replace morpheby/Surge in Package.swift to mattt/Surge to make it work in the meantime.

**Comment by morpheby** [comment]
@johndpope please, verify.

**Comment by johndpope** [comment]
Ok great. Will do. Out with family today. Thanks

**Comment by johndpope** [comment]
bumping into this - 

(tensorflow) ➜  Seconn-Swift git:(master) swift package generate-xcodeproj
Cloning https://github.com/mattt/Surge.git
Resolving https://github.com/mattt/Surge.git at 2.1.0
warning: dependency 'surge' is missing; cloning again
Updating https://github.com/morpheby/NeuralNet-MNIST.git
Updating https://github.com/1024jp/GzipSwift.git
Updating https://github.com/morpheby/Surge.git
Completed resolution in 1.46s
Resolving https://github.com/morpheby/Surge.git at 2.2.0
error: terminated(128): git -C /Users/jpope/Documents/tensorflowWorkspace/Seconn-Swift/.build/checkouts/Surge-cb825e3a checkout -f d5aba295461673dc0f40d2b6c2310cd3e4002701 output:
    fatal: reference is not a tree: d5aba295461673dc0f40d2b6c2310cd3e4002701


tried removing build folder and upgrading carthage 
(also removed resolved file)
Error: carthage 0.30.1 already installed

no joy.

**Comment by johndpope** [comment]
rm -rf .build fixed it. thanks
