### ISSUE TITLE
fyi - playground return error variables currently must have an initial value when entered at the top level of REPL

### ISSUE THREAD

**Issue by johndpope** [morpheby/Seconn-Swift#2]
<img width="1411" alt="screen shot 2018-09-04 at 10 22 42 am" src="https://user-images.githubusercontent.com/289994/45039775-56728800-b032-11e8-8d34-347030d23965.png">

managed to get things to run by nesting the test variable within the do block { }

do {
   let  test = try SeconnTest()

https://gist.github.com/johndpope/ef8c515bf63c0d3eb285d0ad860b8f18

**Comment by dkgrieshammer** [comment]
fiy if you change from "Manually Run" to "Automatically Run" you're still allowed to initialize empty constants/variables - which is even more strange from my point of view
